version: "3.7"

services:
  logistic_db:
    container_name: logistic_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=logistic_db
    image: postgres:15.3-alpine
